import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "Shelfie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`bg-[#F5F3EF]`}
      >
        {children}
        <Footer />
        <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}
